export const tagsRelipa = [
  { title: 'Blockchain development', id: 1 },
  { title: 'NFT', id: 2 },
  { title: 'SES', id: 3 },
  { title: 'Livestreaming app', id: 4 },
  { title: 'DEX', id: 5 },
  { title: 'CEX', id: 6 },
  { title: 'AWS', id: 7 },
  { title: 'PWA', id: 8 },
  { title: 'ICO', id: 9 },
  { title: 'IDO', id: 10 },
  { title: 'OpenSea', id: 11 },
  { title: 'Ethereum', id: 12 },
  { title: 'POC', id: 13 },
  { title: 'DAO', id: 14 },
  { title: 'Cost', id: 15 },
  { title: 'Test engineer', id: 16 },
  { title: 'Play to earn', id: 17 },
  { title: 'Layer model', id: 18 },
  { title: 'Structure', id: 19 },
  { title: 'Metafi', id: 20 },
]
